name: clevrer-vp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.2
  - torchvision>=0.17
  - numpy
  - opencv
  - matplotlib
  - tqdm
  - pillow
  - pip:
      - lpips
      - scikit-image
      - einops
